remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Lab 2
description: In this lab we learned about git and installed it as well as practiced using in it with different commnads. We also used GitHub to clone a repo. 
